package in.spann

import java.io.{PrintWriter, File}
import java.util.Calendar

import scala.io.Source

object FinderAndReplacer {

  val input =
    """|core_trap_clickstream = log_dir_core_core_clickstream_0_trap = "{{log_dir}}/core/core-clickstream/0/trap"
      |core_out_hive_clickstream = raw_clickstream = "{{staged_dir}}/raw/clickstream/"
      |core_clickstream_output = core_core_clickstream_0 = "{{staged_dir}}/core/core-clickstream/0/"
      |core_raw_transaction_output = raw_coretransaction = "{{staged_dir}}/raw/coretransaction/"
      |core_transaction_output = core_core_transaction_0 = "{{staged_dir}}/core/core-transaction/0/"
      |core_sku_input = core_raw_edw_eiv_c_sku_dim = "{{raw_dir}}/edw/eiv_c_sku_dim"
      |core_endeca_collection_path = core_core_endeca_collection_0 = "{{staged_dir}}/core/core-endeca-collection/0"
      |core_enhanced_ecom_product_input_path = core_enhanced_ecom_product_0 = "{{staged_dir}}/core/enhanced-ecom-product/0"
      |core_store_group = core_store_group_0 = "{{staged_dir}}/core/store-group/0"
      |core_trap_clickstream_data = log_dir_core_core_clickstream_0_trap_clickstream_data = "{{log_dir}}/core/core-clickstream/0/trap/clickstream-data/"
      |core_trap_core_sku = log_dir_core_core_sku_0_trap = "{{log_dir}}/core/core-sku/0/trap"
      |core_brand_input = core_raw_edw_eiv_c_brnd_dim = "{{raw_dir}}/edw/eiv_c_brnd_dim"
      |core_color_group_input = core_raw_edw_eiv_c_clor_gp = "{{raw_dir}}/edw/eiv_c_clor_gp"
      |core_color_group_association_input = core_raw_edw_eiv_c_clor_gp_assn = "{{raw_dir}}/edw/eiv_c_clor_gp_assn"
      |trending_ecom_product_path = core_core_ecom_product_0 = "{{staged_dir}}/core/core-ecom-product/0"
      |core_sku_path = core_core_sku_0 = "{{staged_dir}}/core/core-sku/0"
      |core_core_store = core_core_store_0 = "{{staged_dir}}/core/core-store/0"
      |core_trap_sku_pipe = log_dir_core_core_sku_0_trap_sku_pipe = "{{log_dir}}/core/core-sku/0/trap/sku-pipe/"
      |core_trap_brand_pipe = log_dir_core_core_sku_0_trap_brand_pipe = "{{log_dir}}/core/core-sku/0/trap/brand-pipe/"
      |core_trap_color_group_pipe = log_dir_core_core_sku_0_trap_color_group_pipe = "{{log_dir}}/core/core-sku/0/trap/color-group-pipe/"
      |core_core_store_group = core_store_group_0 = "{{staged_dir}}/core/store-group/0"
      |core_trap_color_association_pipe = log_dir_core_core_sku_0_trap_color_association_pipe = "{{log_dir}}/core/core-sku/0/trap/color-association-pipe/"
      |core_trap_sku_avro_output = log_dir_core_core_sku_0_trap_avro_output_pipe = "{{log_dir}}/core/core-sku/0/trap/avro-output-pipe/"
      |core_core_fiscal = core_core_fiscal_0 = "{{staged_dir}}/core/core-fiscal/0"
      |core_trap_fiscal = log_dir_core_core_fiscal_0_trap = "{{log_dir}}/core/core-fiscal/0/trap"
      |core_fiscal_input = core_raw_edw_eiv_c_tm_dim = "{{raw_dir}}/edw/eiv_c_tm_dim"
      |core_fiscal_path = core_core_fiscal_0 = "{{staged_dir}}/core/core-fiscal/0"
      |core_trap_fiscal_pipe = log_dir_core_core_fiscal_0_trap_fiscal_pipe = "{{log_dir}}/core/core-fiscal/0/trap/fiscal-pipe/"
      |core_trap_denorm_product = log_dir_core_denorm_product_0_trap = "{{log_dir}}/core/denorm-product/0/trap"
      |core_atg_kls_product_path = core_raw_ecom_atg_atgprdcata_kls_product = "{{raw_dir}}/ecomAtg/ATGPRDCATA.KLS_PRODUCT"
      |core_atg_dcs_child_sku = core_raw_ecom_atg_atgprdcata_dcs_prd_chldsku = "{{raw_dir}}/ecomAtg/ATGPRDCATA.DCS_PRD_CHLDSKU"
      |core_atg_kls_sku = core_raw_ecom_atg_atgprdcata_kls_sku = "{{raw_dir}}/ecomAtg/ATGPRDCATA.KLS_SKU"
      |core_atg_kls_sku_upc = core_raw_ecom_atg_atgprdcata_kls_sku_upc_relation = "{{raw_dir}}/ecomAtg/ATGPRDCATA.KLS_SKU_UPC_RELATION"
      |core_atg_kls_upc = core_raw_ecom_atg_atgprdcata_kls_upc = "{{raw_dir}}/ecomAtg/ATGPRDCATA.KLS_UPC"
      |core_atg_sku_attribute = core_raw_ecom_atg_atgprdcata_dcs_sku_attr = "{{raw_dir}}/ecomAtg/ATGPRDCATA.DCS_SKU_ATTR"
      |core_atg_dcs_product = core_raw_ecom_atg_atgprdcata_dcs_product = "{{raw_dir}}/ecomAtg/ATGPRDCATA.DCS_PRODUCT"
      |core_zip_to_store = core_zip_to_store_0 = "{{staged_dir}}/core/zip-to-store/0"
      |core_ecom_path = core_raw_ecom_k_est_srch_fnl_prd = "{{raw_dir}}/ecom/k_est_srch_fnl_prd"
      |core_trap_denorm_sku = log_dir_core_denorm_sku_0_trap = "{{log_dir}}/core/denorm-sku/0/trap"
      |core_ecom_sku_path = core_raw_ecom_k_est_srch_fnl_sku = "{{raw_dir}}/ecom/k_est_srch_fnl_sku"
      |core_ecom_sku_output = core_core_ecom_sku_0 = "{{staged_dir}}/core/core-ecom-sku/0"
      |core_trap_ecom_sku_pipe = log_dir_core_core_ecom_sku_0_trap_ecom_sku_pipe = "{{log_dir}}/core/core-ecom-sku/0/trap/ecom-sku-pipe/"
      |core_trap_ecom_product_pipe = log_dir_core_core_ecom_product_0_trap_ecom_product_pipe = "{{log_dir}}/core/core-ecom-product/0/trap/ecom-product-pipe/"
      |core_trap_ecom_order = log_dir_core_core_ecom_order_0_trap = "{{log_dir}}/core/core-ecom-order/0/trap"
      |core_eiv_order = core_raw_edw_eiv_ord = "{{raw_dir}}/edw/eiv_ord"
      |core_core_ecom_order = core_core_ecom_order_0 = "{{staged_dir}}/core/core-ecom-order/0"
      |core_core_recommendation_product_hourly_delta = core_core_recommendation_product_hourly_delta_0 = "{{staged_dir}}/core/core-recommendation-product/hourly-delta/0"
      |core_core_recommendation_product_daily_snapshot = core_core_recommendation_product_daily_snapshot_0 = "{{staged_dir}}/core/core-recommendation-product/daily-snapshot/0"
      |core_trap_mailing_address = log_dir_core_core_mailing_address_0_trap = "{{log_dir}}/core/core-mailing-address/0/trap"
      |core_mailing_adress_path = core_core_mailing_address_0 = "{{staged_dir}}/core/core-mailing-address/0"
      |core_raw_mailing_address_path = core_raw_edw_eiv_malg_addr = "{{raw_dir}}/edw/eiv_malg_addr"
      |core_trap_zip_code = log_dir_core_core_zip_code_0_trap = "{{log_dir}}/core/core-zip-code/0/trap"
      |core_raw_zipcode = core_raw_file_zipcode = "{{raw_dir}}/file/zipcode"
      |core_zipcode_path = core_core_zip_code_0 = "{{staged_dir}}/core/core-zip-code/0"
      |core_trap_core_store = log_dir_core_core_store_0_trap = "{{log_dir}}/core/core-store/0/trap"
      |core_raw_cluster = core_raw_edw_eiv_c_str_clustr_dim = "{{raw_dir}}/edw/eiv_c_str_clustr_dim"
      |core_raw_location = core_raw_edw_eiv_c_loc_dim = "{{raw_dir}}/edw/eiv_c_loc_dim"
      |core_store_path = core_core_store_0 = "{{staged_dir}}/core/core-store/0"
      |core_trap_ecom_order_pipe = log_dir_core_core_ecom_order_0_trap_ecom_order_pipe = "{{log_dir}}/core/core-ecom-order/0/trap/ecom-order-pipe/"
      |core_trap_mailing_address_pipe = log_dir_core_core_mailing_address_0_trap_mailing_address_pipe = "{{log_dir}}/core/core-mailing-address/0/trap/mailing-address-pipe/"
      |core_trap_zip_code_pipe = log_dir_core_core_zip_code_0_trap_zip_code_pipe = "{{log_dir}}/core/core-zip-code/0/trap/zip-code-pipe/"
      |core_trap_store_cluster_pipe = log_dir_core_core_store_0_trap_store_cluster_pipe = "{{log_dir}}/core/core-store/0/trap/store-cluster-pipe/"
      |core_trap_store_data_pipe = log_dir_core_core_store_0_trap_store_data_pipe = "{{log_dir}}/core/core-store/0/trap/store-data-pipe/"
      |core_trap_store_avro_output_pipe = log_dir_core_core_store_0_trap_avro_output_pipe = "{{log_dir}}/core/core-store/0/trap/avro-output-pipe/"
      |core_trap_core_transaction = log_dir_core_core_transaction_0_trap = "{{log_dir}}/core/core-transaction/0/trap"
      |core_enhanced_transaction = core_enhanced_transaction_0 = "{{staged_dir}}/core/enhanced-transaction/0"
      |core_raw_eiv_party_attribute_association = core_raw_edw_eiv_pty_attr_assn = "{{raw_dir}}/edw/eiv_pty_attr_assn"
      |core_raw_eiv_party_attribute = core_raw_edw_eiv_pty_attr = "{{raw_dir}}/edw/eiv_pty_attr"
      |core_raw_eiv_party_address = core_raw_edw_eiv_pty_addr = "{{raw_dir}}/edw/eiv_pty_addr"
      |core_raw_party_email = core_raw_edw_eiv_elctrnc_addr = "{{raw_dir}}/edw/eiv_elctrnc_addr"
      |core_customer = core_core_customer_0 = "{{staged_dir}}/core/core-customer/0"
      |core_trap_core_customer_party_email = log_dir_core_core_customer_0_trap_party_email = "{{log_dir}}/core/core-customer/0/trap/party-email/"
      |core_email_price_only_path = email_price_only = "{{staged_dir}}/email/priceOnly"
      |core_ede_deals_path = ede_deals_0 = "{{staged_dir}}/ede/deals/0"
      |trending_products_each_attribute_base64 = trending_trending_products_from_each_attribute_output_0_merged_product_base64 = "{{staged_dir}}/trending/trendingProductsFromEachAttributeOutput/0/merged-product-base64/"
      |trending_products_output_base64 = trending_trending_products_output_0_merged_product_base64 = "{{staged_dir}}/trending/trendingProductsOutput/0/merged-product-base64/"
      |trending_trap_new_arrival = log_dir_staged_new_arrival_0_trap = "{{log_dir}}/staged/new_arrival/0/trap"
      |trending_trap_seasonal_clickstream = log_dir_staged_seasonal_clickstream = "{{log_dir}}/staged/SeasonalClickstream/"
      |trending_trap_seasonal_view_data_aggregate = log_dir_staged_create_seasonal_views_data_aggregates = "{{log_dir}}/staged/CreateSeasonalViewsDataAggregates/"
      |trending_trap_format_trending_popular_rec = log_dir_staged_format_trending_popular_popular_recommendations = "{{log_dir}}/staged/formatTrendingPopular/popular_recommendations"
      |trending_enhance_transaction_path = core_enhanced_transaction_0 = "{{staged_dir}}/core/enhanced-transaction/0"
      |trending_sum_product_AggregatebystoreId = trending_sum_product_aggregate_by_store_id_0  = "{{staged_dir}}/trending/sum_productAggregateByStoreId/0 "
      |trending_sum_trendingScoreBystoreId = trending_sum_trending_score_by_store_id_0 = "{{staged_dir}}/trending/sum_trendingScoreByStoreId/0"
      |trending_sum_trendingAtrributeLevelScoreByStoreId = trending_sum_trending_attribute_level_score_by_store_id_0 = "{{staged_dir}}/trending/sum_trendingAttributeLevelScoreByStoreId/0"
      |trending_clickstream_view_view = clickstream_view_view_0 = "{{staged_dir}}/clickstream/view-view/0"
      |trending_sum_trending_product_outputByStoreId = trending_sum_trending_products_output_by_store_id_0 = "{{staged_dir}}/trending/sum_trendingProductsOutputByStoreId/0"
      |trending_sum_trendingproductByTopCategoryOutputByStoreId = trending_sum_trending_products_by_top_category_output_by_store_id_0 = "{{staged_dir}}/trending/sum_trendingProductsByTopCategoryOutputByStoreId/0"
      |trending_sum_trendingProductsFromEachCategoryOutputByStoreId = trending_sum_trending_products_from_each_category_output_by_store_id_0 = "{{staged_dir}}/trending/sum_trendingProductsFromEachCategoryOutputByStoreId/0"
      |trending_sum_trendingProductsFromEachAttributeOutputByStoreId = trending_sum_trending_products_from_each_attribute_output_by_store_id_0 = "{{staged_dir}}/trending/sum_trendingProductsFromEachAttributeOutputByStoreId/0"
      |trending_sum_trendingProductsOutputByStoreId_csv  = trending_sum_trending_products_output_by_store_id_0_csv  = "{{staged_dir}}/trending/sum_trendingProductsOutputByStoreId/0/csv "
      |trending_sum_trendingProductsOutputByStoreId_ede = trending_sum_trending_products_output_by_store_id_0_ede = "{{staged_dir}}/trending/sum_trendingProductsOutputByStoreId/0/ede"
      |trending_sum_trendingProductsFromEachAttributeOutputByStoreId_ede = trending_sum_trending_products_from_each_attribute_output_by_store_id_0_ede = "{{staged_dir}}/trending/sum_trendingProductsFromEachAttributeOutputByStoreId/0/ede"
      |trending_sum_trendingProductsFromEachAttributeOutputByStoreId_csv = trending_sum_trending_products_from_each_attribute_output_by_store_id_0_csv = "{{staged_dir}}/trending/sum_trendingProductsFromEachAttributeOutputByStoreId/0/csv"
      |trending_sum_trendingProductsFromEachAttributeOutputByStoreId_consolidated_ede = trending_sum_trending_products_from_each_attribute_output_by_store_id_0_consolidated_ede = "{{staged_dir}}/trending/sum_trendingProductsFromEachAttributeOutputByStoreId/0/consolidated_ede"
      |trending_sum_trendingProductsOutputByStoreId_csv = trending_sum_trending_products_output_by_store_id_0_csv  = "{{staged_dir}}/trending/sum_trendingProductsOutputByStoreId/0/csv "
      |trending_sum_trendingProductsOutputByStoreId_consolidated_ede = trending_sum_trending_products_output_by_store_id_0_consolidated_ede = "{{staged_dir}}/trending/sum_trendingProductsOutputByStoreId/0/consolidated_ede"
      |trending_sum_trendingProductsFromEachCategoryOutputByStoreId_csv = trending_sum_trending_products_from_each_category_output_by_store_id_0_csv = "{{staged_dir}}/trending/sum_trendingProductsFromEachCategoryOutputByStoreId/0/csv"
      |trending_sum_trendingProductsFromEachCategoryOutputByStoreId_consolidated_ede = trending_sum_trending_products_from_each_category_output_by_store_id_0_consolidated_ede  = "{{staged_dir}}/trending/sum_trendingProductsFromEachCategoryOutputByStoreId/0/consolidated_ede "
      |trending_sum_trendingProductsOutputByStoreId_ede_hfiles = trending_sum_trending_products_output_by_store_id_0_ede_hfiles = "{{staged_dir}}/trending/sum_trendingProductsOutputByStoreId/0/ede-hfiles"
      |lookups_ecom_product_lookup_output = lookup_ecom_product_lookup_0 = "{{staged_dir}}/lookup/ecom-product-lookup/0"
      |lookup_store_to_store_group_lookup = lookup_store_to_store_group_lookup_0 = "{{staged_dir}}/lookup/store-to-store-group-lookup/0"
      |lookup_product_category_dump = lookup_product_category_dump_0 = "{{staged_dir}}/lookup/product-category-dump/0"
      |lookup_zip_to_store_lookup = lookup_zip_to_store_lookup_0 = "{{staged_dir}}/lookup/zip-to-store-lookup/0"
      |lookup_zip_to_store_group_lookup = lookup_zip_to_store_group_lookup_0 = "{{staged_dir}}/lookup/zip-to-store-group-lookup/0"
      |lookup_product_to_product_group_lookup = lookup_product_to_product_group_lookup_0 = "{{staged_dir}}/lookup/product-to-product-group-lookup/0"
      |lookup_trap_product_to_product_group_lookup = log_dir_lookup_product_to_product_group_lookup_0_trap = "{{log_dir}}/lookup/product-to-product-group-lookup/0/trap"
      |lookup_top_sku_lookup = lookup_top_sku_lookup_0 = "{{staged_dir}}/lookup/top-sku-lookup/0"
      |lookup_top_sku_inv_lookup = lookup_top_sku_inv_lookup_0 = "{{staged_dir}}/lookup/top-sku-inv-lookup/0"
      |hbaseloader_bulk_load_rec_customer = bulk_load_rec_customer = "{{staged_dir}}/bulk-load/rec-customer"
      |hbaseloader_bulk_load_reports = bulk_load_reports = "{{staged_dir}}/bulk-load/reports"
      |hbaseloader_bulk_load_traps = bulk_load_traps = "{{staged_dir}}/bulk-load/traps"
      |hbaseloader_bulk_load_reports_recommendations_customer = bulk_load_reports_recommendations_customer  = "{{staged_dir}}/bulk-load/reports/recommendations_customer "
      |hbaseloader_bulk_load_rec_customer_hfiles = bulk_load_rec_customer_hfiles = "{{staged_dir}}/bulk-load/rec-customer-hfiles"
      |hbaseloader_bulk_load_rec_propensity = bulk_load_rec_propensity = "{{staged_dir}}/bulk-load/rec-propensity"
      |hbaseloader_bulk_load_reports_propensity = bulk_load_reports_recommendations_propensity  = "{{staged_dir}}/bulk-load/reports/recommendations_propensity "
      |hbaseloader_bulk_load_rec_propensity_hfiles = bulk_load_rec_propensity_hfiles = "{{staged_dir}}/bulk-load/rec-propensity-hfiles"
      |hbaseloader_bulk_load_rec_product = bulk_load_rec_products = "{{staged_dir}}/bulk-load/rec-products"
      |hbaseloader_bulk_load_reports_product = bulk_load_reports_recommendations_product  = "{{staged_dir}}/bulk-load/reports/recommendations_product "
      |hbaseloader_bulk_load_rec_product_hfiles = bulk_load_rec_products_hfiles = "{{staged_dir}}/bulk-load/rec-products-hfiles"
      |hbaseloader_bulk_load_rec_trending = bulk_load_rec_trending = "{{staged_dir}}/bulk-load/rec-trending"
      |hbaseloader_bulk_load_reports_trending = bulk_load_reports_recommendations_trending  = "{{staged_dir}}/bulk-load/reports/recommendations_trending "
      |hbaseloader_bulk_load_rec_trending_hfiles = bulk_load_rec_trending_hfiles = "{{staged_dir}}/bulk-load/rec-trending-hfiles"
      |hbaseloader_bulk_load_rec_customer_hist = bulk_load_rec_customer_hist = "{{staged_dir}}/bulk-load/rec-customer_hist"
      |hbaseloader_bulk_load_reports_customer_hist_recommendations = bulk_load_reports_recommendations_customer_history  = "{{staged_dir}}/bulk-load/reports/recommendations_customer_history "
      |hbaseloader_bulk_load_rec_customer_hist_hfiles = bulk_load_rec_customer_hist_hfiles = "{{staged_dir}}/bulk-load/rec-customer_hist-hfiles"
      |customer_search_personal_affinity_user_propensity = customer_search_personal_affinity_v2_prod_copy_for_reports_0_user_propensity = "{{staged_dir}}/customer/search_personal_affinity_v2_prod_copy_for_reports/0/userPropensity"
      |customer_collab_filtering_cat_output = customer_customer_collaborative_filtering_hbase_input_atg_prod_data_0_category_output_csv = "{{staged_dir}}/customer/customer-collaborative-filtering-hbase-input_atg_PROD_DATA/0/category-output/csv/"
      |customer_profile_output = customer_customer_profile_output_0 = "{{staged_dir}}/customer/customer-profile-output/0"
      |trap_rec_output_processor = log_dir_staged_recommendation_output_processor = "{{log_dir}}/staged/RecommendationOutputProcessor/"
      |trap_rec_output_processor_1_3 = log_dir_staged_recommendation_output_processor_1_3 = "{{log_dir}}/staged/RecommendationOutputProcessor_1_3/"
      |trap_rec_output_processor_1_5 = log_dir_staged_recommendation_output_processor_1_5 = "{{log_dir}}/staged/RecommendationOutputProcessor_1_5/"
      |flpropensity_output = customer_search_personal_affinity_v2_0_fl_propensities = "{{staged_dir}}/customer/search_personal_affinity_v2/0/FL_propensities"
      |search_trap_rec_output_processor_contextual_filtered = log_dir_staged_recommendation_output_processor_process_contextual_filtered_search_output = "{{log_dir}}/staged/RecommendationOutputProcessor_process_contextual_filtered_search_output/"
      |search_trap_rec_output_processor_contextual = log_dir_staged_recommendation_output_processor_process_contextual_search_output = "{{log_dir}}/staged/RecommendationOutputProcessor_process_contextual_search_output/"
      |core_core_ecom_product = core_core_ecom_product_0 = "{{staged_dir}}/core/core-ecom-product/0"
      |core_endeca_sku = core_core_endeca_sku_0 = "{{staged_dir}}/core/core-endeca-sku/0"
      |core_raw_file_path = core_raw_file = "{{raw_dir}}/file"
      |core_raw_file_endeca_product_path = core_raw_file_endeca_product = "{{raw_dir}}/file/endecaProduct"
      |core_raw_file_endeca_sku_path = core_raw_file_sku = "{{raw_dir}}/file/sku"
      |core_raw_file_endeca_product_formatted_output_path = core_raw_file_endeca_product_formatted_output = "{{raw_dir}}/file/endecaProduct/formattedOutput"
      |core_trap_endeca_product = log_dir_core_endeca_product_0_trap = "{{log_dir}}/core/endeca-product/0/trap"
      |core_trap_endeca_sku = log_dir_core_endeca_sku_0_trap = "{{log_dir}}/core/endeca-sku/0/trap"
      |core_trap_endeca_price = log_dir_core_endeca_price_0_trap = "{{log_dir}}/core/endeca-price/0/trap"
      |core_trap_endeca_collection = log_dir_core_endeca_collection_0_trap = "{{log_dir}}/core/endeca-collection/0/trap"
      |core_raw_file_endeca_sku_formatted_output_path = core_raw_file_sku_formatted_output = "{{raw_dir}}/file/sku/formattedOutput"
      |core_endeca_price_path = core_core_endeca_price_0 = "{{staged_dir}}/core/core-endeca-price/0"
      |core_raw_file_endeca_price_path = core_raw_file_endeca_price = "{{raw_dir}}/file/endecaPrice"
      |core_endeca_product_path = core_core_endeca_product_0 = "{{staged_dir}}/core/core-endeca-product/0"
      |core_raw_file_endeca_collection_path = core_raw_file_endeca_collection = "{{raw_dir}}/file/endecaCollection"
      |core_raw_file_endeca_collection_formatted_output_path = core_raw_file_endeca_collection_formatted_output = "{{raw_dir}}/file/endecaCollection/formattedOutput"
      |core_rec_batch_retrieve = recommendation_recommendation_batch_retrieve_0 = "{{staged_dir}}/recommendation/recommendationBatchRetrieve/0/"
      |core_trap_ecom_product = log_dir_core_core_ecom_product_0_trap = "{{log_dir}}/core/core-ecom-product/0/trap"
      |trending_sum_trendingProductsFromEachAttributeOutputByStoreId_ede_hfiles = trending_sum_trending_products_from_each_attribute_output_by_store_id_0_ede_hfiles = "{{staged_dir}}/trending/sum_trendingProductsFromEachAttributeOutputByStoreId/0/ede-hfiles"
      |trending_sum_trendingProductsFromEachCategoryOutputByStoreId_ede = trending_sum_trending_products_from_each_category_output_by_store_id_0_ede = "{{staged_dir}}/trending/sum_trendingProductsFromEachCategoryOutputByStoreId/0/ede"
      |trending_sum_trendingProductsFromEachCategoryOutputByStoreId_ede_hfiles = trending_sum_trending_products_from_each_category_output_by_store_id_0_ede_hfiles = "{{staged_dir}}/trending/sum_trendingProductsFromEachCategoryOutputByStoreId/0/ede-hfiles"
      |trending_productAggregateByStoreId = trending_product_aggregate_by_store_id_0 = "{{staged_dir}}/trending/productAggregateByStoreId/0"
      |trending_trendingScoreByStoreId = trending_trending_score_by_store_id_0 = "{{staged_dir}}/trending/trendingScoreByStoreId/0"
      |trending_trendingAttributeLevelScoreByStoreId = trending_trending_attribute_level_score_by_store_id_0 = "{{staged_dir}}/trending/trendingAttributeLevelScoreByStoreId/0"
      |trending_trendingProductsByTopCategoryOutputByStoreId = trending_trending_products_by_top_category_output_by_store_id_0 = "{{staged_dir}}/trending/trendingProductsByTopCategoryOutputByStoreId/0"
      |trending_trendingProductsFromEachCategoryOutputByStoreId = trending_trending_products_from_each_category_output_by_store_id_0 = "{{staged_dir}}/trending/trendingProductsFromEachCategoryOutputByStoreId/0"
      |trending_trendingProductsFromEachAttributeOutputByStoreId = trending_trending_products_from_each_attribute_output_by_store_id_0 = "{{staged_dir}}/trending/trendingProductsFromEachAttributeOutputByStoreId/0"
      |trending_sum_trendingProductsFromEachAttributeOutputconsolidated_ede = trending_sum_trending_products_from_each_attribute_output_0_consolidated_ede = "{{staged_dir}}/trending/sum_trendingProductsFromEachAttributeOutput/0/consolidated_ede"
      |trending_sum_trendingProductsFromEachCategoryOutputByconsolidated_ede = trending_sum_trending_products_from_each_category_output_by_store_id_0_consolidated_ede = "{{staged_dir}}/trending/sum_trendingProductsFromEachCategoryOutputByStoreId/0/consolidated_ede"
      |trending_sum_trendingProductsFromEachCategoryOutputconsolidated_ede = trending_sum_trending_products_from_each_category_output_0_consolidated_ede = "{{staged_dir}}/trending/sum_trendingProductsFromEachCategoryOutput/0/consolidated_ede"
      |trending_sum_trendingProductsOutputconsolidated_ede = trending_sum_trending_products_output_0_consolidated_ede = "{{staged_dir}}/trending/sum_trendingProductsOutput/0/consolidated_ede"
      |trending_trendingProductsByTopCategoryOutputByStoreldconsolidated_ede = trending_trending_products_by_top_category_output_by_store_id_0_consolidated_ede = "{{staged_dir}}/trending/trendingProductsByTopCategoryOutputByStoreId/0/consolidated_ede"
      |trending_trendingProductsByTopCategoryOutputconsolidated_ede = trending_trending_products_by_top_category_output_0_consolidated_ede = "{{staged_dir}}/trending/trendingProductsByTopCategoryOutput/0/consolidated_ede"
      |trending_trendingProductsFromEachAttributeOutputByStoreId_consolidated_ede = trending_trending_products_from_each_attribute_output_by_store_id_0_consolidated_ede = "{{staged_dir}}/trending/trendingProductsFromEachAttributeOutputByStoreId/0/consolidated_ede"
      |trending_trendingProductsFromEachAttributeOutput_consolidated_ede = trending_trending_products_from_each_attribute_output_0_consolidated_ede = "{{staged_dir}}/trending/trendingProductsFromEachAttributeOutput/0/consolidated_ede"
      |trending_trendingProductsFromEachCategoryOutputByStoreId_consolidated_ede = trending_trending_products_from_each_category_output_by_store_id_0_consolidated_ede = "{{staged_dir}}/trending/trendingProductsFromEachCategoryOutputByStoreId/0/consolidated_ede"
      |trending_trendingProductsFromEachCategoryOutput_consolidated_ede = trending_trending_products_from_each_category_output_0_consolidated_ede = "{{staged_dir}}/trending/trendingProductsFromEachCategoryOutput/0/consolidated_ede"
      |trending_trendingProductsOutput_consolidated_ede = trending_trending_products_output_0_consolidated_ede = "{{staged_dir}}/trending/trendingProductsOutput/0/consolidated_ede"
      |trending_trending_products_by_top_category_output_by_storeId_csv = trending_trending_products_by_top_category_output_by_store_id_0_csv = "{{staged_dir}}/trending/trendingProductsByTopCategoryOutputByStoreId/0/csv"
      |trending_trending_products_by_top_category_output_by_storeId_ede = trending_trending_products_by_top_category_output_by_store_id_0_ede = "{{staged_dir}}/trending/trendingProductsByTopCategoryOutputByStoreId/0/ede"
      |trending_trending_products_from_each_attribute_output_by_storeId_csv = trending_trending_products_from_each_attribute_output_by_store_id_0_csv = "{{staged_dir}}/trending/trendingProductsFromEachAttributeOutputByStoreId/0/csv"
      |trending_trending_products_from_each_attribute_output_by_storeId_ede = trending_trending_products_from_each_attribute_output_by_store_id_0_ede = "{{staged_dir}}/trending/trendingProductsFromEachAttributeOutputByStoreId/0/ede"
      |trending_trending_products_from_each_category_output_by_storeId_csv = trending_trending_products_from_each_category_output_by_store_id_0_csv = "{{staged_dir}}/trending/trendingProductsFromEachCategoryOutputByStoreId/0/csv"
      |trending_trending_products_from_each_category_output_by_storeId_ede = trending_trending_products_from_each_category_output_by_store_id_0_ede = "{{staged_dir}}/trending/trendingProductsFromEachCategoryOutputByStoreId/0/ede"
      |trending_trending_products_by_top_category_output_by_storeId_ede_hfiles = trending_trending_products_by_top_category_output_by_store_id_0_ede_hfiles = "{{staged_dir}}/trending/trendingProductsByTopCategoryOutputByStoreId/0/ede-hfiles"
      |trending_trending_products_from_each_attribute_output_by_storeId_ede_hfiles = trending_trending_products_from_each_attribute_output_by_store_id_0_ede_hfiles = "{{staged_dir}}/trending/trendingProductsFromEachAttributeOutputByStoreId/0/ede-hfiles"
      |trending_trending_products_from_each_category_output_by_storeId_ede_hfiles = trending_trending_products_from_each_category_output_by_store_id_0_ede_hfiles = "{{staged_dir}}/trending/trendingProductsFromEachCategoryOutputByStoreId/0/ede-hfiles"
      |trending_sum_product_aggregate = trending_sum_product_aggregate_0 = "{{staged_dir}}/trending/sum_productAggregate/0"
      |trending_sum_trendingScore = trending_sum_trending_score_0 = "{{staged_dir}}/trending/sum_trendingScore/0"
      |trending_product_aggregate = trending_product_aggregate_0 = "{{staged_dir}}/trending/productAggregate/0"
      |trending_score_output = trending_trending_score_0 = "{{staged_dir}}/trending/trendingScore/0"
      |trending_attribute_level_score = trending_trending_attribute_level_score_0 = "{{staged_dir}}/trending/trendingAttributeLevelScore/0"
      |trending_product_output = trending_trending_products_output_0 = "{{staged_dir}}/trending/trendingProductsOutput/0"
      |trending_products_by_top_category_output = trending_trending_products_by_top_category_output_0 = "{{staged_dir}}/trending/trendingProductsByTopCategoryOutput/0"
      |trending_products_from_each_category_output = trending_trending_products_from_each_category_output_0 = "{{staged_dir}}/trending/trendingProductsFromEachCategoryOutput/0"
      |trending_products_from_each_attribute_output = trending_trending_products_from_each_attribute_output_0 = "{{staged_dir}}/trending/trendingProductsFromEachAttributeOutput/0"
      |trending_products_by_top_category_output_csv = trending_trending_products_by_top_category_output_0_csv = "{{staged_dir}}/trending/trendingProductsByTopCategoryOutput/0/csv"
      |trending_products_by_top_category_output_ede = trending_trending_products_by_top_category_output_0_ede = "{{staged_dir}}/trending/trendingProductsByTopCategoryOutput/0/ede"
      |trending_product_output_csv = trending_trending_products_output_0_csv = "{{staged_dir}}/trending/trendingProductsOutput/0/csv"
      |trending_product_output_ede = trending_trending_products_output_0_ede = "{{staged_dir}}/trending/trendingProductsOutput/0/ede"
      |trending_products_from_each_attribute_output_ede = trending_trending_products_from_each_attribute_output_0_ede = "{{staged_dir}}/trending/trendingProductsFromEachAttributeOutput/0/ede"
      |trending_products_from_each_category_output_csv = trending_trending_products_from_each_category_output_0_csv = "{{staged_dir}}/trending/trendingProductsFromEachCategoryOutput/0/csv"
      |trending_products_from_each_category_output_ede = trending_trending_products_from_each_category_output_0_ede = "{{staged_dir}}/trending/trendingProductsFromEachCategoryOutput/0/ede"
      |trending_products_from_each_attribute_output_csv = trending_trending_products_from_each_attribute_output_0_csv = "{{staged_dir}}/trending/trendingProductsFromEachAttributeOutput/0/csv"
      |ede_deals = ede_deals_0 = "{{staged_dir}}/ede/deals/0"
      |trending_productTrendingDealsSum_dealKey = trending_product_trending_deals_sum_deal_key4_0 = "{{staged_dir}}/trending/productTrendingDealsSum/dealKey4/0"
      |trending_deals_trending_score_sum_dealKey = trending_deals_trending_score_sum_deal_key4_0 = "{{staged_dir}}/trending/deals_trendingScoreSum/dealKey4/0"
      |trending_deals_trending_attribute_level_score_sum_deal_key = trending_deals_trending_attribute_level_score_sum_deal_key4_0 = "{{staged_dir}}/trending/deals_trendingAttributeLevelScoreSum/dealKey4/0"
      |trending_deals_trending_products_output_sum_dealKey = trending_deals_trending_products_output_sum_deal_key4_0 = "{{staged_dir}}/trending/deals_trendingProductsOutputSum/dealKey4/0"
      |trending_deals_trending_products_from_each_attribute_output_sum_deal_key_1 = trending_deals_trending_products_from_each_attribute_output_sum__deal_key1_0 = "{{staged_dir}}/trending/deals_trendingProductsFromEachAttributeOutputSum//dealKey1/0"
      |trending_deals_trending_products_from_each_attribute_output_sum_deal_key_2 = trending_deals_trending_products_from_each_attribute_output_sum__deal_key2_0 = "{{staged_dir}}/trending/deals_trendingProductsFromEachAttributeOutputSum//dealKey2/0"
      |trending_deals_trending_products_from_each_attribute_output_sum_deal_key_3 = trending_deals_trending_products_from_each_attribute_output_sum__deal_key3_0 = "{{staged_dir}}/trending/deals_trendingProductsFromEachAttributeOutputSum//dealKey3/0"
      |trending_deals_trending_products_from_each_attribute_output_sum_deal_key_4 = trending_deals_trending_products_from_each_attribute_output_sum__deal_key4_0 = "{{staged_dir}}/trending/deals_trendingProductsFromEachAttributeOutputSum//dealKey4/0"
      |trending_deals_trending_products_from_each_attribute_output_sum_deal_key_5 = trending_deals_trending_products_from_each_attribute_output_sum__deal_key5_0 = "{{staged_dir}}/trending/deals_trendingProductsFromEachAttributeOutputSum//dealKey5/0"
      |trending_deals_trending_products_from_each_attribute_output_sum_deal_key_6 = trending_deals_trending_products_from_each_attribute_output_sum__deal_key6_0 = "{{staged_dir}}/trending/deals_trendingProductsFromEachAttributeOutputSum//dealKey6/0"
      |trending_deals_trending_products_from_each_attribute_output_sum_deal_key_7 = trending_deals_trending_products_from_each_attribute_output_sum__deal_key7_0 = "{{staged_dir}}/trending/deals_trendingProductsFromEachAttributeOutputSum//dealKey7/0"
      |trending_deals_trending_products_from_each_attribute_output_sum_deal_key_8 = trending_deals_trending_products_from_each_attribute_output_sum__deal_key8_0 = "{{staged_dir}}/trending/deals_trendingProductsFromEachAttributeOutputSum//dealKey8/0"
      |trending_deals_trending_products_from_each_attribute_output_sum_deal_key_9 = trending_deals_trending_products_from_each_attribute_output_sum__deal_key9_0 = "{{staged_dir}}/trending/deals_trendingProductsFromEachAttributeOutputSum//dealKey9/0"
      |trending_deals_trending_products_from_each_attribute_output_sum_deal_key_10 = trending_deals_trending_products_from_each_attribute_output_sum__deal_key10_0 = "{{staged_dir}}/trending/deals_trendingProductsFromEachAttributeOutputSum//dealKey10/0"
      |trending_deals_trending_products_from_each_attribute_output_sum_deal_key_11 = trending_deals_trending_products_from_each_attribute_output_sum__deal_key11_0 = "{{staged_dir}}/trending/deals_trendingProductsFromEachAttributeOutputSum//dealKey11/0"
      |trending_deals_trending_products_from_each_attribute_output_merged = trending_deals_trending_products_from_each_attribute_output_merged_0 = "{{staged_dir}}/trending/deals_trendingProductsFromEachAttributeOutput_merged/0"
      |trending_sum_trending_attribute_level_score = trending_sum_trending_attribute_level_score_0 = "{{staged_dir}}/trending/sum_trendingAttributeLevelScore/0"
      |trending_sum_trendingProductsOutput = trending_sum_trending_products_output_0 = "{{staged_dir}}/trending/sum_trendingProductsOutput/0"
      |trending_sum_trending_products_by_top_category_output = trending_sum_trending_products_by_top_category_output_0 = "{{staged_dir}}/trending/sum_trendingProductsByTopCategoryOutput/0"
      |trending_sum_trending_products_from_each_category_output = trending_sum_trending_products_from_each_category_output_0 = "{{staged_dir}}/trending/sum_trendingProductsFromEachCategoryOutput/0"
      |trending_sum_trending_products_from_each_attribute_output = trending_sum_trending_products_from_each_attribute_output_0 = "{{staged_dir}}/trending/sum_trendingProductsFromEachAttributeOutput/0"
      |trending_sum_trending_products_output_csv = trending_sum_trending_products_output_0_csv = "{{staged_dir}}/trending/sum_trendingProductsOutput/0/csv"
      |trending_sum_trending_products_output_ede = trending_sum_trending_products_output_0_ede = "{{staged_dir}}/trending/sum_trendingProductsOutput/0/ede"
      |trending_sum_trending_products_from_each_attribute_output_csv = trending_sum_trending_products_from_each_attribute_output_0_csv = "{{staged_dir}}/trending/sum_trendingProductsFromEachAttributeOutput/0/csv"
      |trending_sum_trending_products_from_each_attribute_output_ede = trending_sum_trending_products_from_each_attribute_output_0_ede = "{{staged_dir}}/trending/sum_trendingProductsFromEachAttributeOutput/0/ede"
      |trending_sum_trending_products_from_each_category_output_csv = trending_sum_trending_products_from_each_category_output_0_csv = "{{staged_dir}}/trending/sum_trendingProductsFromEachCategoryOutput/0/csv"
      |trending_deals_trending_products_from_each_attribute_output_sum = trending_deals_trending_products_from_each_attribute_output_sum__0 = "{{staged_dir}}/trending/deals_trendingProductsFromEachAttributeOutputSum//0"
      |trending_deals_trending_products_from_each_attribute_output_sum_ede = trending_deals_trending_products_from_each_attribute_output_sum__0_ede = "{{staged_dir}}/trending/deals_trendingProductsFromEachAttributeOutputSum//0/ede"
      |trending_deals_trending_products_from_each_attribute_output_sum_ede_hfiles = trending_deals_trending_products_from_each_attribute_output_sum__0_ede_hfiles = "{{staged_dir}}/trending/deals_trendingProductsFromEachAttributeOutputSum//0/ede-hfiles"
      |trending_sum_trending_products_from_each_category_output_ede = trending_sum_trending_products_from_each_category_output_0_ede = "{{staged_dir}}/trending/sum_trendingProductsFromEachCategoryOutput/0/ede"
      |trending_trending_product_output_by_store_id_csv = trending_trending_products_output_by_store_id_0_csv = "{{staged_dir}}/trending/trendingProductsOutputByStoreId/0/csv"
      |trending_deals_trending_products_from_each_attribute_output_sum_deal_key = trending_deals_trending_products_from_each_attribute_output_sum_deal_key_0 = "{{staged_dir}}/trending/deals_trendingProductsFromEachAttributeOutputSum/dealKey/0"
      |trending_products_by_top_category_output_ede_hfiles = trending_trending_products_by_top_category_output_0_ede_hfiles = "{{staged_dir}}/trending/trendingProductsByTopCategoryOutput/0/ede-hfiles"
      |trending_products_output_ede_hfiles = trending_trending_products_output_0_ede_hfiles = "{{staged_dir}}/trending/trendingProductsOutput/0/ede-hfiles"
      |trending_products_from_each_attribute_output_ede_hfiles = trending_trending_products_from_each_attribute_output_0_ede_hfiles = "{{staged_dir}}/trending/trendingProductsFromEachAttributeOutput/0/ede-hfiles"
      |trending_products_from_each_category_output_ede_hfiles = trending_trending_products_from_each_category_output_0_ede_hfiles = "{{staged_dir}}/trending/trendingProductsFromEachCategoryOutput/0/ede-hfiles"
      |trending_popular_trending_popular_output = trending_popular_trending_popular_0 = "{{staged_dir}}/trending/popular_trending/popular/0"
      |trending_popular_trending_popular_recommendation_formatted = trending_popular_trending_popular_recommendation_formatted_0  = "{{staged_dir}}/trending/popular_trending/popularRecommendationFormatted/0 "
      |trending_popular_trending_popular_recommendation_formatted_csv = trending_popular_trending_popular_recommendation_formatted_0_csv = "{{staged_dir}}/trending/popular_trending/popularRecommendationFormatted/0/csv"
      |trending_popular_trending_popular_recommendation_porcessed_ede = trending_popular_trending_popular_recommendation_porcessed_0_ede = "{{staged_dir}}/trending/popular_trending/popularRecommendationPorcessed/0/ede"
      |trending_trap_popular_recommendations = log_dir_staged_recommendation_output_processor_popular_recommendations = "{{log_dir}}/staged/RecommendationOutputProcessor/popular_recommendations"
      |trending_popular_trending_popular_recommendation_porcessed_consolidated_ede = trending_popular_trending_popular_recommendation_porcessed_0_consolidated_ede = "{{staged_dir}}/trending/popular_trending/popularRecommendationPorcessed/0/consolidated_ede"
      |trending_popular_trending_popular_recommendation_formatted_ede = trending_popular_trending_popular_recommendation_formatted_0_ede = "{{staged_dir}}/trending/popular_trending/popularRecommendationFormatted/0/ede"
      |trending_product_top_trending_deals_deal_key4 = trending_product_top_trending_deals_deal_key4_0 = "{{staged_dir}}/trending/productTopTrendingDeals/dealKey4/0"
      |trending_deals_top_trending_score_deal_key4 = trending_deals_top_trending_score_deal_key4_0 = "{{staged_dir}}/trending/deals_topTrendingScore/dealKey4/0"
      |trending_deals_top_trending_attribute_level_score_deal_key4 = trending_deals_top_trending_attribute_level_score_deal_key4_0 = "{{staged_dir}}/trending/deals_topTrendingAttributeLevelScore/dealKey4/0"
      |trending_deals_top_trending_products_output_deal_key4 = trending_deals_top_trending_products_output_deal_key4_0 = "{{staged_dir}}/trending/deals_topTrendingProductsOutput/dealKey4/0"
      |trending_deals_top_trending_products_by_top_category_output_deal_key4 = trending_deals_top_trending_products_by_top_category_output_deal_key4_0 = "{{staged_dir}}/trending/deals_topTrendingProductsByTopCategoryOutput/dealKey4/0"
      |trending_deals_top_trending_products_from_each_category_output_deal_key4 = trending_deals_top_trending_products_from_each_category_output_deal_key4_0 = "{{staged_dir}}/trending/deals_topTrendingProductsFromEachCategoryOutput/dealKey4/0"
      |trending_sum_trendingProducts_output_ede_hfiles = trending_sum_trending_products_output_0_ede_hfiles = "{{staged_dir}}/trending/sum_trendingProductsOutput/0/ede-hfiles"
      |trending_sum_trending_products_from_each_attribute_output_ede_hfiles = trending_sum_trending_products_from_each_attribute_output_0_ede_hfiles = "{{staged_dir}}/trending/sum_trendingProductsFromEachAttributeOutput/0/ede-hfiles"
      |trending_sum_trending_products_from_each_category_output_ede_hfiles = trending_sum_trending_products_from_each_category_output_0_ede_hfiles = "{{staged_dir}}/trending/sum_trendingProductsFromEachCategoryOutput/0/ede-hfiles"
      |trending_seasonal_clickstream_data_path = seasonal_clickstream_0 = "{{staged_dir}}/seasonal-clickstream/0"
      |trending_deals_sum_score = trending_deals_trending_score_sum = "{{staged_dir}}/trending/deals_trendingScoreSum"
      |trending_deals_sum_attribute_level_score = trending_deals_trending_attribute_level_score_sum = "{{staged_dir}}/trending/deals_trendingAttributeLevelScoreSum"
      |trending_deals_sum_product_output = trending_deals_trending_products_output_sum = "{{staged_dir}}/trending/deals_trendingProductsOutputSum"
      |trending_deals_sum_product_by_top_category_output = trending_deals_trending_products_by_top_category_output_sum = "{{staged_dir}}/trending/deals_trendingProductsByTopCategoryOutputSum"
      |trending_deals_sum_product_from_each_category_output = trending_deals_trending_products_from_each_category_output_sum = "{{staged_dir}}/trending/deals_trendingProductsFromEachCategoryOutputSum"
      |trending_deals_sum_product_from_each_attribute_output = trending_deals_trending_products_from_each_attribute_output_sum = "{{staged_dir}}/trending/deals_trendingProductsFromEachAttributeOutputSum"
      |trending_seasonal_view_aggregate = seasonal_trending_view_aggregate_0 = "{{staged_dir}}/seasonal_trending/viewAggregate/0"
      |trending_seasonal_view_trending_score = seasonal_trending_view_trending_score_0 = "{{staged_dir}}/seasonal_trending/view_trendingScore/0"
      |trending_seasonal_view_trending_attribute_level_score = seasonal_trending_view_trending_attribute_level_score_0 = "{{staged_dir}}/seasonal_trending/view_trendingAttributeLevelScore/0"
      |trending_seasonal_view_trending_product_top_trending_by_all_category_output = seasonal_trending_view_trending_products_top_trending_by_all_category_output_0 = "{{staged_dir}}/seasonal_trending/view_trendingProductsTopTrendingByAllCategoryOutput/0"
      |trending_seasonal_products_by_top_category_output = seasonal_trending_view_trending_products_by_top_category_output_0 = "{{staged_dir}}/seasonal_trending/view_trendingProductsByTopCategoryOutput/0"
      |trending_seasonal_products_from_each_category_output = seasonal_trending_view_trending_products_from_each_category_output_0 = "{{staged_dir}}/seasonal_trending/view_trendingProductsFromEachCategoryOutput/0"
      |trending_seasonal_from_each_attribute_output = seasonal_trending_view_trending_products_from_each_attribute_output_0 = "{{staged_dir}}/seasonal_trending/view_trendingProductsFromEachAttributeOutput/0"
      |trending_seasonal_products_by_top_trending_by_all_category_output_csv = seasonal_trending_view_trending_products_top_trending_by_all_category_output_0_csv = "{{staged_dir}}/seasonal_trending/view_trendingProductsTopTrendingByAllCategoryOutput/0/csv"
      |trending_seasonal_products_output = seasonal_trending_view_trending_products_output_0  = "{{staged_dir}}/seasonal_trending/view_trendingProductsOutput/0 "
      |trending_seasonal_products_output_csv = seasonal_trending_view_trending_products_output_0_csv = "{{staged_dir}}/seasonal_trending/view_trendingProductsOutput/0/csv"
      |trending_seasonal_products_output_ede = seasonal_trending_view_trending_products_output_0_ede = "{{staged_dir}}/seasonal_trending/view_trendingProductsOutput/0/ede"
      |trending_seasonal_products_output_consolidated_ede = seasonal_trending_view_trending_products_output_0_consolidated_ede = "{{staged_dir}}/seasonal_trending/view_trendingProductsOutput/0/consolidated_ede"
      |trending_trap_seasonal_trending_view = log_dir_staged_recommendation_output_processor_seasonal_trending_view = "{{log_dir}}/staged/RecommendationOutputProcessor/seasonal_trending_view"
      |trending_seasonal_products_output_ede_hfiles = seasonal_trending_view_trending_products_output_0_ede_hfiles = "{{staged_dir}}/seasonal_trending/view_trendingProductsOutput/0/ede-hfiles"
      |trending_trending_products_from_each_category_output_merged_product_base = trending_trending_products_from_each_category_output_0_merged_product_base64 = "{{staged_dir}}/trending/trendingProductsFromEachCategoryOutput/0/merged-product-base64"
      |trending_new_arrivals_trending_attribute_level_score = trending_new_arrivals_trending_attribute_level_score_0 = "{{staged_dir}}/trending/new_arrivals_trendingAttributeLevelScore/0"
      |trending_trap_new_arrivals = log_dir_staged_recommendation_output_processor_new_arrivals = "{{log_dir}}/staged/RecommendationOutputProcessor/new_arrivals"
      |trending_deals_top_trending_products_from_each_attribute_output_deal_key1 = trending_deals_top_trending_products_from_each_attribute_output__deal_key1_0 = "{{staged_dir}}/trending/deals_topTrendingProductsFromEachAttributeOutput//dealKey1/0"
      |trending_deals_top_trending_products_from_each_attribute_output_deal_key2 = trending_deals_top_trending_products_from_each_attribute_output__deal_key2_0 = "{{staged_dir}}/trending/deals_topTrendingProductsFromEachAttributeOutput//dealKey2/0"
      |trending_deals_top_trending_products_from_each_attribute_output_deal_key3 = trending_deals_top_trending_products_from_each_attribute_output__deal_key3_0 = "{{staged_dir}}/trending/deals_topTrendingProductsFromEachAttributeOutput//dealKey3/0"
      |trending_deals_top_trending_products_from_each_attribute_output_deal_key4 = trending_deals_top_trending_products_from_each_attribute_output__deal_key4_0 = "{{staged_dir}}/trending/deals_topTrendingProductsFromEachAttributeOutput//dealKey4/0"
      |trending_deals_top_trending_products_from_each_attribute_output_deal_key5 = trending_deals_top_trending_products_from_each_attribute_output__deal_key5_0 = "{{staged_dir}}/trending/deals_topTrendingProductsFromEachAttributeOutput//dealKey5/0"
      |trending_deals_top_trending_products_from_each_attribute_output_deal_key6 = trending_deals_top_trending_products_from_each_attribute_output__deal_key6_0 = "{{staged_dir}}/trending/deals_topTrendingProductsFromEachAttributeOutput//dealKey6/0"
      |trending_deals_top_trending_products_from_each_attribute_output_deal_key7 = trending_deals_top_trending_products_from_each_attribute_output__deal_key7_0 = "{{staged_dir}}/trending/deals_topTrendingProductsFromEachAttributeOutput//dealKey7/0"
      |trending_deals_top_trending_products_from_each_attribute_output_deal_key8 = trending_deals_top_trending_products_from_each_attribute_output__deal_key8_0 = "{{staged_dir}}/trending/deals_topTrendingProductsFromEachAttributeOutput//dealKey8/0"
      |trending_deals_top_trending_products_from_each_attribute_output_deal_key9 = trending_deals_top_trending_products_from_each_attribute_output__deal_key9_0 = "{{staged_dir}}/trending/deals_topTrendingProductsFromEachAttributeOutput//dealKey9/0"
      |trending_deals_top_trending_products_from_each_attribute_output_deal_key10 = trending_deals_top_trending_products_from_each_attribute_output__deal_key10_0 = "{{staged_dir}}/trending/deals_topTrendingProductsFromEachAttributeOutput//dealKey10/0"
      |trending_deals_top_trending_products_from_each_attribute_output_deal_key11 = trending_deals_top_trending_products_from_each_attribute_output__deal_key11_0 = "{{staged_dir}}/trending/deals_topTrendingProductsFromEachAttributeOutput//dealKey11/0"
      |trending_deals_top_trending_products_from_each_attribute_output_merged0 = trending_deals_top_trending_products_from_each_attribute_output_merged_0_csv = "{{staged_dir}}/trending/deals_topTrendingProductsFromEachAttributeOutput_merged/0/csv"
      |trending_deals_top_trending_products_from_each_attribute_output_0_ede = trending_deals_top_trending_products_from_each_attribute_output__0_ede = "{{staged_dir}}/trending/deals_topTrendingProductsFromEachAttributeOutput//0/ede"
      |trending_deals_top_trending_products_from_each_attribute_output_0_consolidated_ede = trending_deals_top_trending_products_from_each_attribute_output__0_consolidated_ede = "{{staged_dir}}/trending/deals_topTrendingProductsFromEachAttributeOutput//0/consolidated_ede"
      |trending_deals_top_trending_products_from_each_attribute_output_0_ede_hfiles = trending_deals_top_trending_products_from_each_attribute_output__0_ede_hfiles = "{{staged_dir}}/trending/deals_topTrendingProductsFromEachAttributeOutput//0/ede-hfiles"
      |trending_product_trending_deals_sum_deal_key9 = trending_product_trending_deals_sum_deal_key9_0 = "{{staged_dir}}/trending/productTrendingDealsSum/dealKey9/0"
      |trending_product_trending_deals_sum_deal_key8 = trending_product_trending_deals_sum_deal_key8_0 = "{{staged_dir}}/trending/productTrendingDealsSum/dealKey8/0"
      |trending_product_trending_deals_sum_deal_key7 = trending_product_trending_deals_sum_deal_key7_0 = "{{staged_dir}}/trending/productTrendingDealsSum/dealKey7/0"
      |trending_product_trending_deals_sum_deal_key6 = trending_product_trending_deals_sum_deal_key6_0 = "{{staged_dir}}/trending/productTrendingDealsSum/dealKey6/0"
      |trending_product_trending_deals_sum_deal_key5 = trending_product_trending_deals_sum_deal_key5_0 = "{{staged_dir}}/trending/productTrendingDealsSum/dealKey5/0"
      |trending_product_trending_deals_sum_deal_key4 = trending_product_trending_deals_sum_deal_key4_0 = "{{staged_dir}}/trending/productTrendingDealsSum/dealKey4/0"
      |trending_product_trending_deals_sum_deal_key3 = trending_product_trending_deals_sum_deal_key3_0 = "{{staged_dir}}/trending/productTrendingDealsSum/dealKey3/0"
      |trending_product_trending_deals_sum_deal_key2 = trending_product_trending_deals_sum_deal_key2_0 = "{{staged_dir}}/trending/productTrendingDealsSum/dealKey2/0"
      |trending_product_trending_deals_sum_deal_key11 = trending_product_trending_deals_sum_deal_key11_0 = "{{staged_dir}}/trending/productTrendingDealsSum/dealKey11/0"
      |trending_product_trending_deals_sum_deal_key10 = trending_product_trending_deals_sum_deal_key10_0 = "{{staged_dir}}/trending/productTrendingDealsSum/dealKey10/0"
      |trending_product_trending_deals_sum_deal_key1 = trending_product_trending_deals_sum_deal_key1_0 = "{{staged_dir}}/trending/productTrendingDealsSum/dealKey1/0"
      |trending_deals_trending_score_sum_deal_key10 = trending_deals_trending_score_sum_deal_key10_0 = "{{staged_dir}}/trending/deals_trendingScoreSum/dealKey10/0"
      |trending_deals_trending_score_sum_deal_key11 = trending_deals_trending_score_sum_deal_key11_0 = "{{staged_dir}}/trending/deals_trendingScoreSum/dealKey11/0"
      |trending_deals_trending_score_sum_deal_key2 = trending_deals_trending_score_sum_deal_key2_0 = "{{staged_dir}}/trending/deals_trendingScoreSum/dealKey2/0"
      |trending_deals_trending_score_sum_deal_key3 = trending_deals_trending_score_sum_deal_key3_0 = "{{staged_dir}}/trending/deals_trendingScoreSum/dealKey3/0"
      |trending_deals_trending_score_sum_deal_key4 = trending_deals_trending_score_sum_deal_key4_0 = "{{staged_dir}}/trending/deals_trendingScoreSum/dealKey4/0"
      |trending_deals_trending_score_sum_deal_key5 = trending_deals_trending_score_sum_deal_key5_0 = "{{staged_dir}}/trending/deals_trendingScoreSum/dealKey5/0"
      |trending_deals_trending_score_sum_deal_key6 = trending_deals_trending_score_sum_deal_key6_0 = "{{staged_dir}}/trending/deals_trendingScoreSum/dealKey6/0"
      |trending_deals_trending_score_sum_deal_key7 = trending_deals_trending_score_sum_deal_key7_0 = "{{staged_dir}}/trending/deals_trendingScoreSum/dealKey7/0"
      |trending_deals_trending_score_sum_deal_key8 = trending_deals_trending_score_sum_deal_key8_0 = "{{staged_dir}}/trending/deals_trendingScoreSum/dealKey8/0"
      |trending_deals_trending_score_sum_deal_key9 = trending_deals_trending_score_sum_deal_key9_0 = "{{staged_dir}}/trending/deals_trendingScoreSum/dealKey9/0"
      |trending_deals_trending_score_sum_deal_key1 = trending_deals_trending_score_sum_deal_key1_0 = "{{staged_dir}}/trending/deals_trendingScoreSum/dealKey1/0"
      |trending_deals_trending_attribute_level_score_sum_deal_key1 = trending_deals_trending_attribute_level_score_sum_deal_key1_0 = "{{staged_dir}}/trending/deals_trendingAttributeLevelScoreSum/dealKey1/0"
      |trending_deals_trending_attribute_level_score_sum_deal_key10 = trending_deals_trending_attribute_level_score_sum_deal_key10_0 = "{{staged_dir}}/trending/deals_trendingAttributeLevelScoreSum/dealKey10/0"
      |trending_deals_trending_attribute_level_score_sum_deal_key11 = trending_deals_trending_attribute_level_score_sum_deal_key11_0 = "{{staged_dir}}/trending/deals_trendingAttributeLevelScoreSum/dealKey11/0"
      |trending_deals_trending_attribute_level_score_sum_deal_key2 = trending_deals_trending_attribute_level_score_sum_deal_key2_0 = "{{staged_dir}}/trending/deals_trendingAttributeLevelScoreSum/dealKey2/0"
      |trending_deals_trending_attribute_level_score_sum_deal_key3 = trending_deals_trending_attribute_level_score_sum_deal_key3_0 = "{{staged_dir}}/trending/deals_trendingAttributeLevelScoreSum/dealKey3/0"
      |trending_deals_trending_attribute_level_score_sum_deal_key4 = trending_deals_trending_attribute_level_score_sum_deal_key4_0 = "{{staged_dir}}/trending/deals_trendingAttributeLevelScoreSum/dealKey4/0"
      |trending_deals_trending_attribute_level_score_sum_deal_key5 = trending_deals_trending_attribute_level_score_sum_deal_key5_0 = "{{staged_dir}}/trending/deals_trendingAttributeLevelScoreSum/dealKey5/0"
      |trending_deals_trending_attribute_level_score_sum_deal_key6 = trending_deals_trending_attribute_level_score_sum_deal_key6_0 = "{{staged_dir}}/trending/deals_trendingAttributeLevelScoreSum/dealKey6/0"
      |trending_deals_trending_attribute_level_score_sum_deal_key7 = trending_deals_trending_attribute_level_score_sum_deal_key7_0 = "{{staged_dir}}/trending/deals_trendingAttributeLevelScoreSum/dealKey7/0"
      |trending_deals_trending_attribute_level_score_sum_deal_key8 = trending_deals_trending_attribute_level_score_sum_deal_key8_0 = "{{staged_dir}}/trending/deals_trendingAttributeLevelScoreSum/dealKey8/0"
      |trending_deals_trending_attribute_level_score_sum_deal_key9 = trending_deals_trending_attribute_level_score_sum_deal_key9_0 = "{{staged_dir}}/trending/deals_trendingAttributeLevelScoreSum/dealKey9/0"
      |customer_kmean_output = customer_customer_profile_output_0_k_mean_clusters_customer_kmeans_k_customer_convergence_threshold = "{{staged_dir}}/customer/customer-profile-output/0/k_mean_clusters_{{customer_kmeans_k}}_{{customer_convergence_threshold}}"
      |customer_k_mean_centroids = customer_customer_profile_output_0_k_mean_centroids_customer_kmeans_k_customer_convergence_threshold = "{{staged_dir}}/customer/customer-profile-output/0/k_mean_centroids_{{customer_kmeans_k}}_{{customer_convergence_threshold}}"
      |customer_prior_cluster_centers = customer_customer_profile_output_0_k_mean_clusters_customer_kmeans_k_customer_convergence_threshold_clusters_customer_num_of_iterations_final = "{{staged_dir}}/customer/customer-profile-output/0/k_mean_clusters_{{customer_kmeans_k}}_{{customer_convergence_threshold}}/clusters-{{customer_num_of_iterations}}-final"
      |similar_kmeans_rec = similar_kmean_0_k_mean_rec = "{{staged_dir}}/similar/kmean/0/k_mean_rec"
      |similar_collection_collection_pig_output = similar_collection_collection_pig_output_0 = "{{staged_dir}}/similar/collection/collection-pig-output/0/"
      |similar_kmean_clean_ecom_product = similar_kmean_0_clean_ecom_product = "{{staged_dir}}/similar/kmean/0/clean-ecom-product/"
      |similar_kmean_seq = similar_kmean_0_seq = "{{staged_dir}}/similar/kmean/0/seq"
      |similar_collection = similar_collection_0 = "{{staged_dir}}/similar/collection/0"
      |similar_kmean_sparse_vec = similar_kmean_0_sparse_vec = "{{staged_dir}}/similar/kmean/0/sparse_vec"
      |similar_collection_csv = similar_collection_0_csv = "{{staged_dir}}/similar/collection/0/csv"
      |similar_collection_ede = similar_collection_0_ede = "{{staged_dir}}/similar/collection/0/ede"
      |similar_kmean_sparse_vec_tfidf_vectors = similar_kmean_0_sparse_vec_tfidf_vectors = "{{staged_dir}}/similar/kmean/0/sparse_vec/tfidf-vectors"
      |similar_kmean_k_mean_clusters = similar_kmean_0_k_mean_clusters = "{{staged_dir}}/similar/kmean/0/k_mean_clusters"
      |similar_kmean_k_mean_centroids = similar_kmean_0_k_mean_centroids = "{{staged_dir}}/similar/kmean/0/k_mean_centroids"
      |similar_kmean_k_mean_rec_csv = similar_kmean_0_k_mean_rec_csv = "{{staged_dir}}/similar/kmean/0/k_mean_rec/csv"
      |similar_collection_ede_hfiles = similar_collection_0_ede_hfiles = "{{staged_dir}}/similar/collection/0/ede-hfiles"
      |similar_kmean_k_mean_rec = similar_kmean_0_k_mean_rec = "{{staged_dir}}/similar/kmean/0/k_mean_rec"
      |similar_kmean_k_mean_clusters_clustered_points = similar_kmean_0_k_mean_clusters_clustered_points = "{{staged_dir}}/similar/kmean/0/k_mean_clusters/clusteredPoints"
      |similar_kmean_k_mean_rec_ede = similar_kmean_0_k_mean_rec_ede = "{{staged_dir}}/similar/kmean/0/k_mean_rec/ede"
      |similar_kmean_k_mean_rec_lock = similar_kmean_0_k_mean_rec__lock = "{{staged_dir}}/similar/kmean/0/k_mean_rec/_lock"
      |similar_kmean_k_mean_rec_ede_hfiles = similar_kmean_0_k_mean_rec_ede_hfiles = "{{staged_dir}}/similar/kmean/0/k_mean_rec/ede-hfiles"
      |contextual_config_stopwordlist = contextual_config_stopwordlist_txt = ""
      |core_clickstream_plm_setup_property_path = mft_incoming_path = ""
      |customer_anony_search_personal_affinity_0 = mft_incoming_path = ""
      """".stripMargin


  val input3 =
    """
      |customer_anony_search_personal_affinity_0_by_atg = customer_anony_search_personal_affinity_0__by_atg = ""
      |customer_anony_search_personal_affinity_0_by_atg = customer_anony_search_personal_affinity_0__by_atg = ""
    """.stripMargin

  def main(args: Array[String]) {
    val lines = (input3).split("\n").toList.filter(!_.trim.isEmpty)
    lines.foreach { line =>
      if (line != "") {
        val parts = line.split("=").map(_.trim)
        val (oldVariable, newVariable) = (parts(0), parts(1))

//        replaceOldVariableToNewRecEngine(oldVariable, newVariable)
        replaceOldVariableToNewConfig(oldVariable, newVariable)
      }
    }
  }

  def replaceOldVariableToNewRecEngine(oldVariable: String, newVariable: String): Unit = {
    val files = Common.getAllFiles("/Users/tkmacgf/sunil/projects/bigdata-recommendation-engine", ".*.gradle$")
    files.foreach { file =>
      println("Processing file: " + file)
      val f1 = new File(file) // Original File
    val f2 = new File("/tmp/" + Calendar.getInstance().getTimeInMillis) // Temporary File
    val w = new PrintWriter(f2)
      Source.fromFile(f1).getLines().toList
        .map { x =>
        x.replaceAllLiterally(s"{$oldVariable}", s"{$newVariable}")
      }
        .foreach(x => w.println(x))
      w.close()
      f2.renameTo(f1)
    }


  }

  def replaceOldVariableToNewConfig(oldVariable: String, newVariable: String): Unit = {
    val files = List("/Users/tkmacgf/sunil/projects/bigdata-recommendation-engine-config/config/gcp-lle/ddh-uat/variables.yml")
    files.foreach { file =>
      println("Processing file: " + file)
      val f1 = new File(file) // Original File
    val f2 = new File("/tmp/" + Calendar.getInstance().getTimeInMillis) // Temporary File
    val w = new PrintWriter(f2)
      Source.fromFile(f1).getLines().toList
        .map { x =>
        x.replaceAllLiterally(s"$oldVariable", s"$newVariable")
      }
        .foreach(x => w.println(x))
      w.close()
      f2.renameTo(f1)
    }
  }
}
